OLED.init(128, 64)
BMP280.Address(BMP280_I2C_ADDRESS.ADDR_0x76)
BMP280.PowerOn()
basic.forever(function () {
    OLED.writeString("T:")
    OLED.writeNum(BMP280.temperature())
    OLED.writeString(" ")
    basic.pause(1000)
    OLED.clear()
})
basic.forever(function () {
    radio.sendString("" + (BMP280.pressure()))
    basic.showString("T:")
    basic.showNumber(BMP280.temperature())
    basic.showString("P:")
    basic.showNumber(BMP280.pressure())
})
basic.forever(function () {
    OLED.writeString("P:")
    OLED.writeNum(BMP280.pressure())
    OLED.writeString(" ")
    basic.pause(1000)
    OLED.clear()
})
